name: Run linters

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, edited]
    branches:
      - main
env:
  DATABASE_URL: 'file:./dev.db'
  APP_PORT: '3000'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Add .env file
        run: echo "DATABASE_URL=file:./dev.db\nAPP_PORT=3000" > .env
        
      - name: Install dependencies
        run: yarn install

      - name: Run Linters
        run:  yarn run lint

